### PR TITLE
Make extension work with Jitsi as a Service

### PR DESCRIPTION
**Pull request by nochiel**
This PR is for the Chatbot functionality.

It ensures it can install when an LNBits manifest includes the extension.

It allows the administrator can configure Jitsi to use the hosted Jitsi as a Service. This is necessary due to a change Jitsi made whereby intergrating with Jitsi has limited features and conferences have limited duration unless jaas is used.

### CODE REVIEW

**Comment by nochiel** [comment]
@dni Please check the permissions on this repo. I don't have access to push changes.

**Comment by nochiel** [comment]
My nostr is: `npub1f3plgr8hr7xqf22jwzgrvdghahqlp98jklzwrjrmvrzpnfvq25js4xzznz`

**Comment by dni** [comment]
> @dni Please check the permissions on this repo. I don't have access to push changes.

we should do it via pull request anyway, easier to review. i gave you access to create new branches.

do you want this pr to be merged? i did not so much changes in it.

**Review by dni — APPROVED** [review]

**Comment by nochiel** [comment]
> > @dni Please check the permissions on this repo. I don't have access to push changes.
> 
> we should do it via pull request anyway, easier to review. i gave you access to create new branches.
> 

Thanks. That makes sense. PRs also make it easier for me to keep track of what's in review.

> do you want this pr to be merged? i did not so much changes in it.

Yes, it's ready to be merged. After which we can tag it and create a release so it's installable for those who want to test it.

**Pull request merged**
